CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS entry (
    id VARCHAR(25) PRIMARY KEY,
    bookNumber INT NOT NULL,
    slipNumber INT NOT NULL,
    source VARCHAR(25) NOT NULL,
    date DATE NOT NULL,
    name VARCHAR(255) NOT NULL,
    site VARCHAR(244) NOT NULL,
    lorryNumber VARCHAR(14) NOT NULL,
    item VARCHAR(255) NOT NULL,
    measurementUnit VARCHAR(50) NOT NULL,
    quantity DECIMAL(10,3) NOT NULL,
    rate DECIMAL(10,2) DEFAULT 0,
    amount DECIMAL(10,2) DEFAULT 0,
    discount DECIMAL(10,2) DEFAULT 0,
    freight DECIMAL(10,2) DEFAULT 0,
    taxPercent DECIMAL(5,2) DEFAULT 0,
    taxAmount DECIMAL(10,2) DEFAULT 0,
    totalAmount DECIMAL(10,2) DEFAULT 0,
    paymentStatus VARCHAR(25) NOT NULL,
    cashCredit DECIMAL(10,2) DEFAULT 0,
    bankCredit DECIMAL(10,2) DEFAULT 0,
    dueAmount DECIMAL(10,2) DEFAULT 0,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    createdDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdatedBy VARCHAR(255) NOT NULL,
    createdBy VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    entryId VARCHAR(25) NOT NULL,
    field VARCHAR(50) NOT NULL,
    oldValue VARCHAR(255),
    newValue VARCHAR(255),
    createdDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    createdBy VARCHAR(255) NOT NULL,
    CONSTRAINT fk_history_entry FOREIGN KEY (entryId) REFERENCES entry(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS item_rate (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    item_name VARCHAR(255) NOT NULL,
    measurement_unit VARCHAR(50) NOT NULL,
    rate DECIMAL(10,2) NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_item_rate (item_name, measurement_unit)
);

CREATE TABLE IF NOT EXISTS user_work_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NULL,
    user_name VARCHAR(255) NOT NULL,
    user_email VARCHAR(255) NULL,
    action_type VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(255) NULL,
    details JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
