ALTER TABLE entry ADD COLUMN IF NOT EXISTS orderStatus VARCHAR(25) NOT NULL DEFAULT 'Active' AFTER paymentStatus;
ALTER TABLE entry ADD COLUMN IF NOT EXISTS cancelledAt DATETIME NULL AFTER orderStatus;
ALTER TABLE entry ADD COLUMN IF NOT EXISTS cancelledBy VARCHAR(255) NULL AFTER cancelledAt;

ALTER TABLE normal_order_entry ADD COLUMN IF NOT EXISTS orderStatus VARCHAR(25) NOT NULL DEFAULT 'Active' AFTER paymentStatus;
ALTER TABLE normal_order_entry ADD COLUMN IF NOT EXISTS cancelledAt DATETIME NULL AFTER orderStatus;
ALTER TABLE normal_order_entry ADD COLUMN IF NOT EXISTS cancelledBy VARCHAR(255) NULL AFTER cancelledAt;

ALTER TABLE b2b_order_entry ADD COLUMN IF NOT EXISTS orderStatus VARCHAR(25) NOT NULL DEFAULT 'Active' AFTER paymentStatus;
ALTER TABLE b2b_order_entry ADD COLUMN IF NOT EXISTS cancelledAt DATETIME NULL AFTER orderStatus;
ALTER TABLE b2b_order_entry ADD COLUMN IF NOT EXISTS cancelledBy VARCHAR(255) NULL AFTER cancelledAt;
