ALTER TABLE entry ADD COLUMN IF NOT EXISTS is_printed TINYINT(1) NOT NULL DEFAULT 0 AFTER orderStatus;
ALTER TABLE normal_order_entry ADD COLUMN IF NOT EXISTS is_printed TINYINT(1) NOT NULL DEFAULT 0 AFTER orderStatus;
ALTER TABLE b2b_order_entry ADD COLUMN IF NOT EXISTS is_printed TINYINT(1) NOT NULL DEFAULT 0 AFTER orderStatus;
