ALTER TABLE customer_account ADD COLUMN IF NOT EXISTS gstin VARCHAR(32) NOT NULL DEFAULT '' AFTER phone;

ALTER TABLE entry ADD COLUMN IF NOT EXISTS gross DECIMAL(10,3) NOT NULL DEFAULT 0 AFTER quantity;
ALTER TABLE entry ADD COLUMN IF NOT EXISTS tare DECIMAL(10,3) NOT NULL DEFAULT 0 AFTER gross;
ALTER TABLE entry ADD COLUMN IF NOT EXISTS net DECIMAL(10,3) NOT NULL DEFAULT 0 AFTER tare;
ALTER TABLE entry ADD COLUMN IF NOT EXISTS remarks VARCHAR(255) NOT NULL DEFAULT '' AFTER source;
ALTER TABLE entry ADD COLUMN IF NOT EXISTS customerGstin VARCHAR(32) NULL AFTER customerAccountName;

ALTER TABLE normal_order_entry ADD COLUMN IF NOT EXISTS gross DECIMAL(10,3) NOT NULL DEFAULT 0 AFTER quantity;
ALTER TABLE normal_order_entry ADD COLUMN IF NOT EXISTS tare DECIMAL(10,3) NOT NULL DEFAULT 0 AFTER gross;
ALTER TABLE normal_order_entry ADD COLUMN IF NOT EXISTS net DECIMAL(10,3) NOT NULL DEFAULT 0 AFTER tare;
ALTER TABLE normal_order_entry ADD COLUMN IF NOT EXISTS remarks VARCHAR(255) NOT NULL DEFAULT '' AFTER source;
ALTER TABLE normal_order_entry ADD COLUMN IF NOT EXISTS customerGstin VARCHAR(32) NULL AFTER source;

ALTER TABLE b2b_order_entry ADD COLUMN IF NOT EXISTS gross DECIMAL(10,3) NOT NULL DEFAULT 0 AFTER quantity;
ALTER TABLE b2b_order_entry ADD COLUMN IF NOT EXISTS tare DECIMAL(10,3) NOT NULL DEFAULT 0 AFTER gross;
ALTER TABLE b2b_order_entry ADD COLUMN IF NOT EXISTS net DECIMAL(10,3) NOT NULL DEFAULT 0 AFTER tare;
ALTER TABLE b2b_order_entry ADD COLUMN IF NOT EXISTS remarks VARCHAR(255) NOT NULL DEFAULT '' AFTER source;
ALTER TABLE b2b_order_entry ADD COLUMN IF NOT EXISTS customerGstin VARCHAR(32) NULL AFTER customerAccountName;
